# Generated by Django 6.0 on 2026-10-03 14:58

import django.core.validators
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, verbose_name='Вступление')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='О клубе')),
                ('figures', wagtail.fields.StreamField([('figure', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: 6, 1200, 40+', 'label': 'Число', 'max_length': 20}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись под числом', 'max_length': 80}), 2: ('wagtail.blocks.StructBlock', [[('value', 0), ('label', 1)]], {'icon': 'pick', 'label': 'Цифра с подписью'})}, help_text='Например: 6 лет возим, 1200 довольных клиентов, 40+ выездов за сезон.', verbose_name='Цифры')),
                ('gallery', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото'})}, help_text='Команда, автобусы, наши выезды.', verbose_name='Фотографии')),
                ('details', wagtail.fields.RichTextField(blank=True, help_text='ИНН, ОГРН, банковские реквизиты, режим работы.', verbose_name='Реквизиты и подробности')),
            ],
            options={
                'verbose_name': 'о клубе',
                'verbose_name_plural': 'о клубе',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Текст перед формой')),
                ('telegram', models.CharField(blank=True, max_length=120, verbose_name='Telegram')),
                ('whatsapp', models.CharField(blank=True, max_length=120, verbose_name='WhatsApp')),
                ('max_link', models.CharField(blank=True, max_length=200, verbose_name='MAX')),
                ('phone', models.CharField(blank=True, max_length=60, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=120, verbose_name='Почта')),
                ('address', models.CharField(blank=True, max_length=120, verbose_name='Город отправления')),
                ('work_hours', models.CharField(blank=True, help_text='Например: «ежедневно с 9:00 до 21:00».', max_length=120, verbose_name='Режим работы')),
            ],
            options={
                'verbose_name': 'контакты',
                'verbose_name_plural': 'контакты',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=60, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('destination', models.CharField(blank=True, help_text='Какое направление выбрал человек в форме.', max_length=160, verbose_name='Направление')),
                ('departure_date', models.CharField(blank=True, help_text='Какую дату выбрал человек в форме.', max_length=60, verbose_name='Дата выезда')),
                ('message', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Получена')),
                ('handled', models.BooleanField(default=False, verbose_name='Обработана')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DestinationIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Одно-два предложения под заголовком каталога.', verbose_name='Вступление')),
            ],
            options={
                'verbose_name': 'каталог направлений',
                'verbose_name_plural': 'каталоги направлений',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('meeting_points', wagtail.fields.StreamField([('point', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Город', 'max_length': 80}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Адрес или ориентир', 'max_length': 200}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Время сбора', 'max_length': 40, 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Комментарий', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('city', 0), ('address', 1), ('time', 2), ('note', 3)]], {'icon': 'site', 'label': 'Точка сбора'})}, help_text='Где и во сколько собираемся.', verbose_name='Точки сбора')),
                ('notes', wagtail.fields.StreamField([('note', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Что учесть', 'max_length': 120}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Подробности', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {'icon': 'help', 'label': 'Заметка'})}, help_text='Парковка, раздевалки, душ, питание, Wi-Fi.', verbose_name='Что учесть')),
            ],
            options={
                'verbose_name': 'как добраться',
                'verbose_name_plural': 'как добраться',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Текст документа')),
            ],
            options={
                'verbose_name': 'юридический документ',
                'verbose_name_plural': 'юридические документы',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, help_text='Короткая строка под названием. Например: «Дикий пляж в сосновом бору».', max_length=160, verbose_name='Подзаголовок')),
                ('kind', models.CharField(choices=[('beach', 'Пляж'), ('wild_beach', 'Дикий пляж'), ('mountains', 'Горы'), ('city', 'Город')], default='beach', help_text='По типу фильтруется каталог. Он же подписывается плашкой на карточке.', max_length=16, verbose_name='Тип')),
                ('eyebrow', models.CharField(blank=True, help_text='Например: «Анапа · 120 км от города». Можно оставить пустым.', max_length=80, verbose_name='Надпись над заголовком')),
                ('price_from', models.CharField(blank=True, help_text='Только число, можно с пробелом: 1 900. Без знака ₽.', max_length=20, verbose_name='Цена «от», ₽')),
                ('duration', models.CharField(default='1 день', help_text='Например: «1 день» или «2 дня / 1 ночь».', max_length=60, verbose_name='Длительность')),
                ('distance', models.CharField(blank=True, help_text='Например: «120 км».', max_length=40, verbose_name='Расстояние')),
                ('travel_time', models.CharField(blank=True, help_text='Например: «2,5 ч».', max_length=40, verbose_name='Время в пути')),
                ('parking', models.CharField(blank=True, help_text='Например: «платная, 300 ₽/день».', max_length=80, verbose_name='Парковка')),
                ('summary', models.TextField(blank=True, help_text='Одно-два предложения: что это и зачем сюда ехать.', verbose_name='Коротко о направлении')),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Развёрнутый текст: что там, чем отличается, что увидит человек.', verbose_name='Подробное описание')),
                ('highlights', wagtail.fields.StreamField([('items', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Пункт'}), 1: ('wagtail.blocks.ListBlock', (0,), {})})),
                ('included', wagtail.fields.StreamField([('items', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Пункт'}), 1: ('wagtail.blocks.ListBlock', (0,), {})})),
                ('excluded', wagtail.fields.StreamField([('items', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Пункт'}), 1: ('wagtail.blocks.ListBlock', (0,), {})})),
                ('packing', wagtail.fields.StreamField([('items', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Пункт'}), 1: ('wagtail.blocks.ListBlock', (0,), {})})),
                ('programme', wagtail.fields.StreamField([('day', 4)], blank=True, block_lookup={0: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Номер дня. Если не заполнять, день подставится по порядку.', 'label': 'День', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Что происходит', 'max_length': 160}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Подробности'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото дня', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('day_number', 0), ('title', 1), ('text', 2), ('image', 3)]], {'icon': 'date', 'label': 'День программы', 'template': 'blocks/day_block.html'})}, help_text='Только для поездок с ночёвкой. Для однодневных выездов не нужно.', verbose_name='Программа')),
                ('stay', wagtail.fields.StreamField([('place', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: «Гоститель Сутки»', 'label': 'Название', 'max_length': 120}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: «гостиница · 1 ночь у моря»', 'label': 'Тип и ночи', 'max_length': 80, 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('name', 1), ('kind', 2), ('text', 3)]], {'icon': 'site', 'label': 'Место ночёвки', 'template': 'blocks/stay_block.html'})}, help_text='Для поездок с ночёвкой: гостиница, апартаменты, коттедж.', verbose_name='Где остановиться')),
                ('gallery_hero', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото'})}, help_text='3–6 широких фотографий. Первая идёт на первый экран страницы.', verbose_name='Фото для первого экрана')),
                ('gallery', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото'})}, help_text='До 10 фотографий. Первые 4–5 соберут мозаику на странице.', verbose_name='Галерея')),
                ('cover', models.ForeignKey(blank=True, help_text='Главное фото направления. Без него карточка в каталоге будет пустой.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'направление',
                'verbose_name_plural': 'направления',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='DestinationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='trips.destination', verbose_name='направление')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'verbose_name': 'метка направления',
                'verbose_name_plural': 'метки направлений',
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='trips.DestinationTag', to='taggit.Tag', verbose_name='Метки'),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_eyebrow', models.CharField(default='Краснодарский край · выезды каждые выходные', max_length=80, verbose_name='Надпись над заголовком')),
                ('hero_title', models.CharField(default='Нескучные выходные', max_length=80, verbose_name='Заголовок первого экрана')),
                ('hero_subtitle', models.TextField(blank=True, help_text='Одно-два предложения: что это и ради чего.', verbose_name='Подзаголовок')),
                ('hero_cta_text', models.CharField(default='Смотреть направления', max_length=40, verbose_name='Текст главной кнопки')),
                ('hero_images', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото'})}, help_text='2–3 фото для правой части первого экрана.', verbose_name='Остальные фото коллажа')),
                ('body', wagtail.fields.StreamField([('nearest', 3), ('manifest', 12), ('grid', 15), ('steps', 22), ('photos', 26), ('features', 32), ('quote', 35), ('faq', 41), ('cta', 46)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Ближайшие выезды', 'label': 'Заголовок', 'max_length': 120}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Подпись под заголовком', 'required': False}), 2: ('wagtail.blocks.IntegerBlock', (), {'default': 6, 'label': 'Сколько показать', 'max_value': 12, 'min_value': 1}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('limit', 2)]], {'icon': 'date', 'label': 'Ближайшие выезды', 'template': 'blocks/nearest_departures.html'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Крупное число или слово', 'max_length': 8, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Мелкая подпись', 'max_length': 80, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 200}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Текст'}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Значение', 'max_length': 20}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'max_length': 80}), 10: ('wagtail.blocks.StructBlock', [[('value', 8), ('label', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Цифры', 'max_num': 4, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('numeral', 4), ('eyebrow', 5), ('heading', 6), ('body', 7), ('stats', 11)]], {'icon': 'doc-full', 'label': 'Блок о клубе', 'template': 'blocks/manifest.html'}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'Куда едем', 'label': 'Заголовок', 'max_length': 120}), 14: ('wagtail.blocks.IntegerBlock', (), {'default': 1, 'label': 'Сколько крупных карточек', 'max_value': 4, 'min_value': 0}), 15: ('wagtail.blocks.StructBlock', [[('heading', 13), ('subheading', 1), ('featured_count', 14)]], {'icon': 'image', 'label': 'Направления плитками', 'template': 'blocks/destination_grid.html'}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Как проходит поездка', 'label': 'Заголовок', 'max_length': 120}), 17: ('wagtail.blocks.CharBlock', (), {'label': 'Время', 'max_length': 20}), 18: ('wagtail.blocks.CharBlock', (), {'label': 'Что происходит', 'max_length': 120}), 19: ('wagtail.blocks.TextBlock', (), {'label': 'Подробности', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('time', 17), ('title', 18), ('text', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'label': 'Шаги', 'max_num': 8}), 22: ('wagtail.blocks.StructBlock', [[('heading', 16), ('items', 21)]], {'icon': 'tasks', 'label': 'Как проходит поездка', 'template': 'blocks/steps.html'}), 23: ('wagtail.blocks.CharBlock', (), {'default': 'Мы там были', 'label': 'Заголовок', 'max_length': 120}), 24: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото'}), 25: ('wagtail.blocks.StreamBlock', [[('image', 24)]], {'label': 'Фотографии'}), 26: ('wagtail.blocks.StructBlock', [[('heading', 23), ('subheading', 1), ('images', 25)]], {'icon': 'image', 'label': 'Фото-стена', 'template': 'blocks/photo_wall.html'}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'Почему с нами', 'label': 'Заголовок', 'max_length': 120}), 28: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 120}), 29: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('title', 28), ('text', 29)]], {}), 31: ('wagtail.blocks.ListBlock', (30,), {'label': 'Пункты', 'max_num': 6}), 32: ('wagtail.blocks.StructBlock', [[('heading', 27), ('items', 31)]], {'icon': 'tick', 'label': 'Почему с нами', 'template': 'blocks/features.html'}), 33: ('wagtail.blocks.TextBlock', (), {'label': 'Цитата или обещание'}), 34: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'max_length': 120, 'required': False}), 35: ('wagtail.blocks.StructBlock', [[('text', 33), ('author', 34)]], {'icon': 'openquote', 'label': 'Цитата', 'template': 'blocks/quote.html'}), 36: ('wagtail.blocks.CharBlock', (), {'default': 'Частые вопросы', 'label': 'Заголовок', 'max_length': 120}), 37: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос', 'max_length': 200}), 38: ('wagtail.blocks.TextBlock', (), {'label': 'Ответ', 'required': False}), 39: ('wagtail.blocks.StructBlock', [[('question', 37), ('answer', 38)]], {}), 40: ('wagtail.blocks.ListBlock', (39,), {'label': 'Вопросы', 'max_num': 10}), 41: ('wagtail.blocks.StructBlock', [[('heading', 36), ('items', 40)]], {'icon': 'help', 'label': 'Частые вопросы', 'template': 'blocks/faq.html'}), 42: ('wagtail.blocks.CharBlock', (), {'default': 'Выходные ещё есть', 'label': 'Заголовок', 'max_length': 200}), 43: ('wagtail.blocks.TextBlock', (), {'label': 'Текст под заголовком', 'required': False}), 44: ('wagtail.blocks.CharBlock', (), {'default': 'Записаться', 'label': 'Текст кнопки', 'max_length': 40}), 45: ('wagtail.blocks.CharBlock', (), {'help_text': 'Оставьте пустым — кнопка поведёт на страницу контактов.', 'label': 'Куда ведёт кнопка', 'max_length': 200, 'required': False}), 46: ('wagtail.blocks.StructBlock', [[('heading', 42), ('text', 43), ('button_text', 44), ('button_url', 45)]], {'icon': 'link', 'label': 'Призыв записаться', 'template': 'blocks/cta.html'})}, help_text='Главная собирается из блоков. Их можно менять местами и удалять.', verbose_name='Блоки страницы')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Широкое фото 2400×1400 или шире — левая часть коллажа.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Большое фото первого экрана')),
            ],
            options={
                'verbose_name': 'главная',
                'verbose_name_plural': 'главные',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='День, когда группа собирается и выезжает.', verbose_name='Дата выезда')),
                ('end_date', models.DateField(blank=True, help_text='Для однодневных поездок можно оставить пустым.', null=True, verbose_name='Дата возвращения')),
                ('price', models.PositiveIntegerField(help_text='Только число, без ₽. Например: 1900', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена за человека, ₽')),
                ('price_note', models.CharField(blank=True, help_text='Например: «при бронировании за 3 дня −10%». Нет скидки — оставьте пустым.', max_length=80, verbose_name='Пометка к цене')),
                ('seats_total', models.PositiveSmallIntegerField(default=40, help_text='Сколько человек помещается в автобус или группу.', validators=[django.core.validators.MaxValueValidator(200)], verbose_name='Всего мест')),
                ('seats_left', models.PositiveSmallIntegerField(default=40, help_text='Сколько мест ещё можно продать.', verbose_name='Свободно мест')),
                ('meeting_point', models.CharField(blank=True, help_text='Например: «ТЦ, парковка у фонтана, вход со стороны Movieplex».', max_length=160, verbose_name='Где собираемся')),
                ('meeting_time', models.TimeField(blank=True, help_text='Во сколько участники должны быть на месте.', null=True, verbose_name='Время сбора')),
                ('status', models.CharField(choices=[('planned', 'Планируется'), ('sold_out', 'Мест нет'), ('cancelled', 'Отменён'), ('done', 'Прошёл')], default='planned', help_text='«Мест нет» — выезд виден в расписании с пометкой. «Отменён» — не показывается на сайте.', max_length=16, verbose_name='Состояние')),
                ('note', models.TextField(blank=True, help_text='Служебное поле. На сайте не выводится.', verbose_name='Комментарий для команды')),
                ('destination', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='trips.destination', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'выезд',
                'verbose_name_plural': 'выезды',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['start_date', 'status'], name='trips_depar_start_d_48e3bb_idx')],
            },
        ),
    ]
