# Generated by Django 6.0 on 2026-10-04 16:05

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalpage',
            name='intro',
            field=models.TextField(blank=True, help_text='Одна строка для списка документов.', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='toc',
            field=wagtail.fields.RichTextField(blank=True, help_text='Список разделов документа. Если оставить пустым, оглавление не выводится.', verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='legalpage',
            name='updated',
            field=models.CharField(default='октябрь 2026', help_text='Например: «октябрь 2026». Показывается в списке и на странице.', max_length=60, verbose_name='Дата редакции'),
        ),
    ]
