# Generated by Django 6.0 on 2026-10-04 16:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_legalpage_intro_legalpage_toc_legalpage_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='faq',
            field=wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Ответ', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})}),
        ),
    ]
