# Generated by Django 6.0 on 2026-10-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_destination_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='distance_km',
            field=models.PositiveIntegerField(blank=True, help_text='Числом — по нему работает фильтр «до 100 / 100–200 / дальше 200 км».', null=True, verbose_name='Расстояние, км'),
        ),
        migrations.AddField(
            model_name='destination',
            name='ew_days',
            field=models.CharField(blank=True, help_text='Через запятую, как в макете: «пт,сб,вс».', max_length=40, verbose_name='Дни выездов'),
        ),
        migrations.AddField(
            model_name='destination',
            name='ew_duration',
            field=models.CharField(default='day', help_text='day — один день, night — с ночёвкой.', max_length=16, verbose_name='Длительность по макету'),
        ),
        migrations.AddField(
            model_name='destination',
            name='ew_type',
            field=models.CharField(default='beach', help_text='Ключ фильтра каталога: micro, wild, beach, mountain, city.', max_length=16, verbose_name='Тип по макету'),
        ),
    ]
