# Generated by Django 6.0 on 2026-10-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_destination_distance_km_destination_ew_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalpage',
            name='toc',
        ),
    ]
