# Generated by Django 6.0 on 2026-10-05 14:15

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_remove_legalpage_toc'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='format',
            field=models.CharField(choices=[('one_day', 'Однодневный'), ('overnight', 'С ночёвкой'), ('excursion', 'Экскурсия')], default='one_day', help_text='Однодневный, с ночёвкой или экскурсия. От формата зависит заголовок программы на странице тура.', max_length=16, verbose_name='Формат поездки'),
        ),
        migrations.AddField(
            model_name='destination',
            name='timeline',
            field=wagtail.fields.StreamField([('step', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: «6:00» или «19:30». Можно оставить пустым.', 'label': 'Время', 'max_length': 20, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: «Сбор и отправление».', 'label': 'Что происходит', 'max_length': 160}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Подробности'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Необязательно. Обычно хватает фото в галерее.', 'label': 'Фото шага', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('time', 0), ('title', 1), ('text', 2), ('image', 3)]], {'icon': 'time', 'label': 'Шаг линии времени', 'template': 'blocks/timeline_step_block.html'})}, help_text='Программа по часам: «6:00 — Сбор», «13:00 — Обед» и так далее. Порядок блоков и есть порядок шагов.', verbose_name='Линия времени'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='programme',
            field=wagtail.fields.StreamField([('day', 4)], blank=True, block_lookup={0: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Номер дня. Если не заполнять, день подставится по порядку.', 'label': 'День', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Что происходит', 'max_length': 160}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Подробности'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото дня', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('day_number', 0), ('title', 1), ('text', 2), ('image', 3)]], {'icon': 'date', 'label': 'День программы', 'template': 'blocks/day_block.html'})}, help_text='Только для поездок с ночёвкой. Для однодневных не нужно.', verbose_name='Программа по дням'),
        ),
    ]
