# Generated by Django 6.0 on 2026-10-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_move_programme_to_timeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='ew_duration',
        ),
        migrations.AlterField(
            model_name='destination',
            name='ew_days',
            field=models.CharField(blank=True, help_text='Через запятую: «пт,сб,вс». Попадает в подзаголовок на странице тура.', max_length=40, verbose_name='Дни выездов'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='ew_type',
            field=models.CharField(choices=[('micro', 'Микропляж'), ('wild', 'Дикий пляж'), ('beach', 'Пляж'), ('mountain', 'Горы'), ('city', 'Город')], default='beach', help_text='По нему фильтруется каталог и подписывается плашка на карточке.', max_length=16, verbose_name='Тип в фильтре каталога'),
        ),
    ]
