# Generated by Django 6.0 on 2026-10-06 16:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_clear_placeholder_destination_covers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='timeline',
            field=wagtail.fields.StreamField([('step', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: «6:00» или «19:30». Для второго дня многодневной поездки допишите «+1»: «6:00 +1» — такие шаги собираются в аккордеон «День 1 / День 2». Можно оставить пустым.', 'label': 'Время', 'max_length': 20, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: «Сбор и отправление».', 'label': 'Что происходит', 'max_length': 160}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Подробности'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Необязательно. Обычно хватает фото в галерее.', 'label': 'Фото шага', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('time', 0), ('title', 1), ('text', 2), ('image', 3)]], {'icon': 'time', 'label': 'Шаг линии времени', 'template': 'blocks/timeline_step_block.html'})}, help_text='Программа по часам: «6:00 — Сбор», «13:00 — Обед» и так далее. Порядок блоков и есть порядок шагов.', verbose_name='Линия времени'),
        ),
    ]
