# Generated by Django 6.0 on 2026-10-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_alter_destination_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='phone_2',
            field=models.CharField(blank=True, default='8 909 465 68 15', help_text='Показывается вторым номером в контактах и в подвале сайта. Оставьте пустым — номер не выводится.', max_length=60, verbose_name='Второй телефон'),
        ),
    ]
