# Generated by Django 6.0 on 2026-10-08 15:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_contactpage_phone_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='meeting_cities',
            field=wagtail.fields.StreamField([('city', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Город', 'max_length': 80}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: <6:30>. Если время ещё уточняете — оставьте пустым.', 'label': 'Время сбора', 'max_length': 40, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: «пл. Урицкого, у памятника».', 'label': 'Точка сбора', 'max_length': 160, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('city', 0), ('time', 1), ('place', 2)]], {'icon': 'site', 'label': 'Город сбора'})}, help_text='Если выезд собирается из разных городов — время для каждого города свое: Майкоп 6:30, Краснодар 7:00. Пустой список — блок не показывается.', verbose_name='Сбор по городам'),
        ),
    ]
