# Generated by Django 6.0 on 2026-10-08 16:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_destination_meeting_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='program_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Только для однодневных: вся программа одним текстом — пишите и форматируйте как удобно. Для многодневных дней — блоки «Линия времени».', verbose_name='Программа текстом'),
        ),
    ]
